version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: petmatch_postgres
    restart: always
    environment:
      POSTGRES_USER: petmatch
      POSTGRES_PASSWORD: petmatch123
      POSTGRES_DB: petmatchdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
